### ISSUE TITLE
Stuck in HA - Its probably me!

### ISSUE THREAD

**Issue by harvey813** [robbrad/UKBinCollectionData#1002]
### Home Assistant Version

Latest

### Installation Method

Using HACS

### Name of Council (if relevant)

Blaby District Council

### Issue Information

Hi! I'm struggling to get this to add, this is the HA log entry, I am fairly convinced its me not inputting something correctly, but I am stuck!

Here is what i've Currently got in each field

data collection: python collect_data.py BlabyDistrictCouncil https://www.blaby.gov.uk -u 1000****1785
UPRN: 1000****1785 (stars added for security)
Time to wait: 60s
JSON to map Bin Type: no idea what to put in here :(

Thank you in advance!
 

Here is the HA log:

Logger: custom_components.uk_bin_collection
Source: custom_components/uk_bin_collection/__init__.py:250
integration: UK Bin Collection Data ([documentation](https://github.com/robbrad/UKBinCollectionData/wiki), [issues](https://github.com/robbrad/UKBinCollectionData/issues))
First occurred: 7:01:21 AM (33 occurrences)
Last logged: 7:22:50 AM

[UKBinCollection] Unexpected error: No connection adapters were found for 'python collect_data.py BlabyDistrictCouncil https://www.blaby.gov.uk -u 1000****1785'
[UKBinCollection] Unexpected error: No connection adapters were found for 'python collect_data.py BlabyDistrictCouncil https://www.blaby.gov.uk -u XXXXXXXX'
Traceback (most recent call last):
  File "/config/custom_components/uk_bin_collection/__init__.py", line 250, in _async_update_data
    data = await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 81, in get_and_parse_data
    page = self.get_data(address_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 124, in get_data
    full_page = requests.get(url, headers, verify=False, timeout=120)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for 'python collect_data.py BlabyDistrictCouncil https://www.blaby.gov.uk -u 1000****1785'

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.12/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by harvey813** [comment]
Thank you! That seems really obvious now!
