### ISSUE TITLE
Issue with Cotswold District data retreval 

### ISSUE THREAD

**Issue by jones-d** [robbrad/UKBinCollectionData#1022]
### Name of Council

Cotswold District Council 

### Issue Information

Originally was working correctly, but unable to obtain bin data

This error originated from a custom integration.

Logger: custom_components.uk_bin_collection
Source: custom_components/uk_bin_collection/__init__.py:250
integration: UK Bin Collection Data (documentation, issues)
First occurred: 11:47:05 (1 occurrences)
Last logged: 11:47:05

[UKBinCollection] Unexpected error: Message: Stacktrace: GetHandleVerifier [0x01105093+25075] (No symbol) [0x0108E124] (No symbol) [0x00F6BE63] (No symbol) [0x00FAFD06] (No symbol) [0x00FAFF4B] (No symbol) [0x00FED8C2] (No symbol) [0x00FD1EC4] (No symbol) [0x00FEB48E] (No symbol) [0x00FD1C16] (No symbol) [0x00FA3F3C] (No symbol) [0x00FA4ECD] GetHandleVerifier [0x013F2523+3094147] GetHandleVerifier [0x01405754+3172532] GetHandleVerifier [0x013FDF32+3141778] GetHandleVerifier [0x011A2100+668256] (No symbol) [0x01096C4D] (No symbol) [0x01093DF8] (No symbol) [0x01093F95] (No symbol) [0x01086C80] BaseThreadInitThunk [0x766A0419+25] RtlGetAppContainerNamedObjectPath [0x77D377FD+237] RtlGetAppContainerNamedObjectPath [0x77D377CD+189]
Traceback (most recent call last):
  File "/config/custom_components/uk_bin_collection/__init__.py", line 250, in _async_update_data
    data = await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 82, in get_and_parse_data
    bin_data_dict = self.parse_data(page, url=address_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/CotswoldDistrictCouncil.py", line 43, in parse_data
    address_entry_field = wait.until(
                          ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x01105093+25075]
	(No symbol) [0x0108E124]
	(No symbol) [0x00F6BE63]
	(No symbol) [0x00FAFD06]
	(No symbol) [0x00FAFF4B]
	(No symbol) [0x00FED8C2]
	(No symbol) [0x00FD1EC4]
	(No symbol) [0x00FEB48E]
	(No symbol) [0x00FD1C16]
	(No symbol) [0x00FA3F3C]
	(No symbol) [0x00FA4ECD]
	GetHandleVerifier [0x013F2523+3094147]
	GetHandleVerifier [0x01405754+3172532]
	GetHandleVerifier [0x013FDF32+3141778]
	GetHandleVerifier [0x011A2100+668256]
	(No symbol) [0x01096C4D]
	(No symbol) [0x01093DF8]
	(No symbol) [0x01093F95]
	(No symbol) [0x01086C80]
	BaseThreadInitThunk [0x766A0419+25]
	RtlGetAppContainerNamedObjectPath [0x77D377FD+237]
	RtlGetAppContainerNamedObjectPath [0x77D377CD+189]

Here is the log file from the Selenium server 
[log.json](https://github.com/user-attachments/files/17790219/log.json) and a screenshot 
<img width="345" alt="image" src="https://github.com/user-attachments/assets/3f37c429-fb61-46d3-bdce-f7a122b5c857">
It looks to be failing to scrape the content correctly

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by jones-d** [comment]
Additional, as this has been a issue, I think the council is blocking my address you can use 15, GL56 0GB to test.

**Comment by jones-d** [comment]
Checked, the website has changed, I have updated, tested and submitted an update.
