### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by idarkside** [robbrad/UKBinCollectionData#1063]
### Home Assistant Version

2024.11.1

### Installation Method

Using HACS

### Name of Council (if relevant)

Kirklees Council

### Issue Information

the component never finishes initialisation after last major update (bin colours)

`This error originated from a custom integration.

Logger: custom_components.uk_bin_collection
Source: custom_components/uk_bin_collection/__init__.py:250
integration: UK Bin Collection Data (documentation, issues)
First occurred: November 25, 2024 at 10:11:03 PM (6669 occurrences)
Last logged: 10:31:53 PM

[UKBinCollection] Unexpected error: Message: Stacktrace: #0 0x55cd10d25133 <unknown> #1 0x55cd10a59966 <unknown> #2 0x55cd10a960dc <unknown> #3 0x55cd10a96211 <unknown> #4 0x55cd10ad06c4 <unknown> #5 0x55cd10ab5bfd <unknown> #6 0x55cd10ace1c7 <unknown> #7 0x55cd10ab59a3 <unknown> #8 0x55cd10a8a46a <unknown> #9 0x55cd10a8b55e <unknown> #10 0x55cd10ce4cae <unknown> #11 0x55cd10ce88fe <unknown> #12 0x55cd10cf1f20 <unknown> #13 0x55cd10ce9923 <unknown> #14 0x55cd10cbcc0e <unknown> #15 0x55cd10d0cb08 <unknown> #16 0x55cd10d0cc97 <unknown> #17 0x55cd10d1d113 <unknown> #18 0x7fcbd7ed6b43 <unknown>
[UKBinCollection] Unexpected error: Message: Stacktrace: #0 0x55efbda8c133 <unknown> #1 0x55efbd7c0966 <unknown> #2 0x55efbd7fd0dc <unknown> #3 0x55efbd7fd211 <unknown> #4 0x55efbd8376c4 <unknown> #5 0x55efbd81cbfd <unknown> #6 0x55efbd8351c7 <unknown> #7 0x55efbd81c9a3 <unknown> #8 0x55efbd7f146a <unknown> #9 0x55efbd7f255e <unknown> #10 0x55efbda4bcae <unknown> #11 0x55efbda4f8fe <unknown> #12 0x55efbda58f20 <unknown> #13 0x55efbda50923 <unknown> #14 0x55efbda23c0e <unknown> #15 0x55efbda73b08 <unknown> #16 0x55efbda73c97 <unknown> #17 0x55efbda84113 <unknown> #18 0x7f3cbc509b43 <unknown>
[UKBinCollection] Unexpected error: Message: Stacktrace: #0 0x55799f98f133 <unknown> #1 0x55799f6c3966 <unknown> #2 0x55799f7000dc <unknown> #3 0x55799f700211 <unknown> #4 0x55799f73a6c4 <unknown> #5 0x55799f71fbfd <unknown> #6 0x55799f7381c7 <unknown> #7 0x55799f71f9a3 <unknown> #8 0x55799f6f446a <unknown> #9 0x55799f6f555e <unknown> #10 0x55799f94ecae <unknown> #11 0x55799f9528fe <unknown> #12 0x55799f95bf20 <unknown> #13 0x55799f953923 <unknown> #14 0x55799f926c0e <unknown> #15 0x55799f976b08 <unknown> #16 0x55799f976c97 <unknown> #17 0x55799f987113 <unknown> #18 0x7fbeaede7b43 <unknown>
[UKBinCollection] Unexpected error: Message: Stacktrace: #0 0x5568ecf25133 <unknown> #1 0x5568ecc59966 <unknown> #2 0x5568ecc960dc <unknown> #3 0x5568ecc96211 <unknown> #4 0x5568eccd06c4 <unknown> #5 0x5568eccb5bfd <unknown> #6 0x5568eccce1c7 <unknown> #7 0x5568eccb59a3 <unknown> #8 0x5568ecc8a46a <unknown> #9 0x5568ecc8b55e <unknown> #10 0x5568ecee4cae <unknown> #11 0x5568ecee88fe <unknown> #12 0x5568ecef1f20 <unknown> #13 0x5568ecee9923 <unknown> #14 0x5568ecebcc0e <unknown> #15 0x5568ecf0cb08 <unknown> #16 0x5568ecf0cc97 <unknown> #17 0x5568ecf1d113 <unknown> #18 0x7f3218b09b43 <unknown>
[UKBinCollection] Unexpected error: Message: Stacktrace: #0 0x558047231133 <unknown> #1 0x558046f65966 <unknown> #2 0x558046fa20dc <unknown> #3 0x558046fa2211 <unknown> #4 0x558046fdc6c4 <unknown> #5 0x558046fc1bfd <unknown> #6 0x558046fda1c7 <unknown> #7 0x558046fc19a3 <unknown> #8 0x558046f9646a <unknown> #9 0x558046f9755e <unknown> #10 0x5580471f0cae <unknown> #11 0x5580471f48fe <unknown> #12 0x5580471fdf20 <unknown> #13 0x5580471f5923 <unknown> #14 0x5580471c8c0e <unknown> #15 0x558047218b08 <unknown> #16 0x558047218c97 <unknown> #17 0x558047229113 <unknown> #18 0x7f6c16cc5b43 <unknown>
Traceback (most recent call last):
  File "/config/custom_components/uk_bin_collection/__init__.py", line 250, in _async_update_data
    data = await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 82, in get_and_parse_data
    bin_data_dict = self.parse_data(page, url=address_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/KirkleesCouncil.py", line 41, in parse_data
    return self._parse_data(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/KirkleesCouncil.py", line 74, in _parse_data
    wait_for_element(
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/KirkleesCouncil.py", line 18, in wait_for_element
    wait_for_element_conditions(driver, element_present, timeout=timeout)
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/KirkleesCouncil.py", line 23, in wait_for_element_conditions
    WebDriverWait(driver, timeout).until(conditions)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5582d34cb133 <unknown>
#1 0x5582d31ff966 <unknown>
#2 0x5582d323c0dc <unknown>
#3 0x5582d323c211 <unknown>
#4 0x5582d32766c4 <unknown>
#5 0x5582d325bbfd <unknown>
#6 0x5582d32741c7 <unknown>
#7 0x5582d325b9a3 <unknown>
#8 0x5582d323046a <unknown>
#9 0x5582d323155e <unknown>
#10 0x5582d348acae <unknown>
#11 0x5582d348e8fe <unknown>
#12 0x5582d3497f20 <unknown>
#13 0x5582d348f923 <unknown>
#14 0x5582d3462c0e <unknown>
#15 0x5582d34b2b08 <unknown>
#16 0x5582d34b2c97 <unknown>
#17 0x5582d34c3113 <unknown>
#18 0x7faa5bcefb43 <unknown>
`

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.12/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by idarkside** [comment]
will this be updated?

**Comment by idarkside** [comment]
i have updated the URL and attempted to reconfigure but it looks like it is not accepting my custom selenium server and instead is trying to connect to http://172.18.0.6:4444/ 

`
[UKBinCollection] Unexpected error: Message: unknown error: cannot create temp dir for user data dir Stacktrace: #0 0x562065841133 <unknown> #1 0x562065575966 <unknown> #2 0x56206559d60d <unknown> #3 0x56206559b07b <unknown> #4 0x5620655da9ad <unknown> #5 0x5620655da18f <unknown> #6 0x5620655d19a3 <unknown> #7 0x5620655a646a <unknown> #8 0x5620655a755e <unknown> #9 0x562065800cae <unknown> #10 0x5620658048fe <unknown> #11 0x56206580df20 <unknown> #12 0x562065805923 <unknown> #13 0x5620657d8c0e <unknown> #14 0x562065828b08 <unknown> #15 0x562065828c97 <unknown> #16 0x562065839113 <unknown> #17 0x7f449f1d3b43 <unknown>
[UKBinCollection] Unexpected error: Message: unknown error: cannot create temp dir for user data dir Stacktrace: #0 0x564a6862f133 <unknown> #1 0x564a68363966 <unknown> #2 0x564a6838b60d <unknown> #3 0x564a6838907b <unknown> #4 0x564a683c89ad <unknown> #5 0x564a683c818f <unknown> #6 0x564a683bf9a3 <unknown> #7 0x564a6839446a <unknown> #8 0x564a6839555e <unknown> #9 0x564a685eecae <unknown> #10 0x564a685f28fe <unknown> #11 0x564a685fbf20 <unknown> #12 0x564a685f3923 <unknown> #13 0x564a685c6c0e <unknown> #14 0x564a68616b08 <unknown> #15 0x564a68616c97 <unknown> #16 0x564a68627113 <unknown> #17 0x7fe4d50a3b43 <unknown>
[UKBinCollection] Unexpected error: Message: unknown error: cannot create temp dir for user data dir Stacktrace: #0 0x56495d47b133 <unknown> #1 0x56495d1af966 <unknown> #2 0x56495d1d760d <unknown> #3 0x56495d1d507b <unknown> #4 0x56495d2149ad <unknown> #5 0x56495d21418f <unknown> #6 0x56495d20b9a3 <unknown> #7 0x56495d1e046a <unknown> #8 0x56495d1e155e <unknown> #9 0x56495d43acae <unknown> #10 0x56495d43e8fe <unknown> #11 0x56495d447f20 <unknown> #12 0x56495d43f923 <unknown> #13 0x56495d412c0e <unknown> #14 0x56495d462b08 <unknown> #15 0x56495d462c97 <unknown> #16 0x56495d473113 <unknown> #17 0x7f9fc4b5ab43 <unknown>
[UKBinCollection] Unexpected error: Message: unknown error: cannot create temp dir for user data dir Stacktrace: #0 0x564751ad5133 <unknown> #1 0x564751809966 <unknown> #2 0x56475183160d <unknown> #3 0x56475182f07b <unknown> #4 0x56475186e9ad <unknown> #5 0x56475186e18f <unknown> #6 0x5647518659a3 <unknown> #7 0x56475183a46a <unknown> #8 0x56475183b55e <unknown> #9 0x564751a94cae <unknown> #10 0x564751a988fe <unknown> #11 0x564751aa1f20 <unknown> #12 0x564751a99923 <unknown> #13 0x564751a6cc0e <unknown> #14 0x564751abcb08 <unknown> #15 0x564751abcc97 <unknown> #16 0x564751acd113 <unknown> #17 0x7fddb6cd9b43 <unknown>
[UKBinCollection] Unexpected error: Message: wait: http://172.18.0.4:4444/ does not respond in 30s
Traceback (most recent call last):
  File "/config/custom_components/uk_bin_collection/__init__.py", line 250, in _async_update_data
    data = await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ~~~~~~~~~~~~~~~~^
        council_module.CouncilClass(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        council_module_str=self.parsed_args.module,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 82, in get_and_parse_data
    bin_data_dict = self.parse_data(page, url=address_url, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/councils/KirkleesCouncil.py", line 41, in parse_data
    return self._parse_data(*args, **kwargs)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/councils/KirkleesCouncil.py", line 63, in _parse_data
    self._driver = driver = create_webdriver(
                            ~~~~~~~~~~~~~~~~^
        web_driver=kwargs["web_driver"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        headless=kwargs.get("headless", True),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        session_name=__name__,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/common.py", line 324, in create_webdriver
    return webdriver.Remote(command_executor=web_driver, options=options)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: wait: http://172.18.0.6:4444/ does not respond in 30s
`

**Comment by planetcastle** [comment]
It's a completely different source.  The previous working version was hosted by Kirklees themselves on their own website.  they now use a platform called Granicus (previously Firmstep).

**Comment by dp247** [comment]
I can make this work for the next collection of each bin, if that's good?
