### ISSUE TITLE
pandas._libs.pandas_parser

### ISSUE THREAD

**Issue by matt2005** [robbrad/UKBinCollectionData#1079]
### Home Assistant Version

2024.12.2

### Installation Method

Using HACS

### Issue Information

When updating to 2024.12.4 upon restart the below is reported.

```
Logger: homeassistant.setup
Source: setup.py:334
First occurred: 22:11:14 (1 occurrences)
Last logged: 22:11:14

Setup failed for custom integration 'uk_bin_collection': Unable to import component: No module named 'pandas._libs.pandas_parser'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/uk_bin_collection/__init__.py", line 18, in <module>
    from uk_bin_collection.uk_bin_collection.collect_data import UKBinCollectionApp
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 6, in <module>
    from uk_bin_collection.uk_bin_collection.get_bin_data import (
    ...<2 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 14, in <module>
    from uk_bin_collection.uk_bin_collection.common import update_input_json
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/common.py", line 9, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.13/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
    ...<62 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
    ...<4 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/pandas/_libs/__init__.py", line 16, in <module>
    import pandas._libs.pandas_parser  # isort: skip # type: ignore[reportUnusedImport]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pandas._libs.pandas_parser'
```

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.12/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by matt2005** [comment]
Appears to now be resolved in HA 2025.2.2
