### ISSUE TITLE
Integration no longer works/sets up since recent update

### ISSUE THREAD

**Issue by cadwizzard** [robbrad/UKBinCollectionData#1084]
### Home Assistant Version

2024.12.3

### Installation Method

Using HACS

### Name of Council (if relevant)

West Lindsey District Council

### Issue Information

The integration will not start and results in an error. I have tried deleting the address and setting it up from scratch. I'm running the latest prompted version.
`Logger: custom_components.uk_bin_collection
Source: custom_components/uk_bin_collection/__init__.py:250
integration: UK Bin Collection Data ([documentation](https://github.com/robbrad/UKBinCollectionData/wiki), [issues](https://github.com/robbrad/UKBinCollectionData/issues))
First occurred: 15 December 2024 at 10:48:01 (1353 occurrences)
Last logged: 17:31:03

[UKBinCollection] Unexpected error: can only concatenate str (not "relativedelta") to str
Traceback (most recent call last):
  File "/config/custom_components/uk_bin_collection/__init__.py", line 250, in _async_update_data
    data = await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ~~~~~~~~~~~~~~~~^
        council_module.CouncilClass(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        council_module_str=self.parsed_args.module,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 82, in get_and_parse_data
    bin_data_dict = self.parse_data(page, url=address_url, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/uk_bin_collection/uk_bin_collection/councils/WestLindseyDistrictCouncil.py", line 101, in parse_data
    full_date = bin_date + relativedelta(years=1)
                ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "relativedelta") to str`

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.12/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by cadwizzard** [comment]
It could entirely be the council, I only see the integration on my dashboard visibility at certain days just before the bins are due collected.
It the time of year they plan calendars for next year too.

Are you on the fix, or do you need me to create a different issue under 'council issue' ?

**Comment by robbrad** [comment]
No don't make a new issue we can rename this one

**Comment by cadwizzard** [comment]
Just wanted to say thanks to dp247 for working on this (I notice you modded the code with a house number and different postcode to fix it):
![image](https://github.com/user-attachments/assets/a57d6252-51f3-431b-b3b1-838286e11c74)

I've not made any integration updates yet, and it started working immediately after midnight on the 1st Jan 2025 when it retried:

![image](https://github.com/user-attachments/assets/baf159d0-845a-4eaf-8503-2c9940a95812)

The bin 'Colour' always shows as black for all bins, but I use the other colour entity in my cards anyway :)

![Screenshot 2025-01-01 120947](https://github.com/user-attachments/assets/f83289ee-263c-49d2-a809-43211774e450)



This works: 
type: entity-filter
entities:
  - entity: sensor.lyndarlea_lodge_black
    name: Black
  - entity: sensor.lyndarlea_lodge_blue
    name: Blue
  - entity: sensor.lyndarlea_lodge_purple
    name: Purple
