### ISSUE TITLE
Could not locate element with visible text

### ISSUE THREAD

**Issue by andy-81** [robbrad/UKBinCollectionData#481]
### Home Assistant Version

2023.12.2

### Installation Method

Using HACS

### Name of Council (if relevant)

Buckinghamshire County Council

### Issue Information

I have tried using selenium both via the add-on store in home assistant and via docker on a separate system but both provide the same error message. I am sure it is something I am doing wrong but am scratching my head trying to work out what it is and how I could fix it. 

Below is the log from home assistant which shows the error, I entered the information into the HA prompts as per the documentation on the wiki with no success, I am trying to work out if there is a way for me to test it from the command line in HA at present but have not been able to locate the location of the python scripts to run as per the wiki. 

Any help would be appreciated. 

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
Integration: Sensor (documentation, issues)
First occurred: 21:24:54 (4 occurrences)
Last logged: 21:35:08

Error while setting up uk_bin_collection platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/uk_bin_collection/sensor.py", line 122, in _async_update_data
    data = await self.hass.async_add_executor_job(self.ukbcd.run)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 82, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 69, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 69, in template_method
    bin_data_dict = self.parse_data(
                    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/councils/BuckinghamshireCouncil.py", line 63, in parse_data
    inputElement_ad.select_by_visible_text(user_paon)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/support/select.py", line 137, in select_by_visible_text
    raise NoSuchElementException(f"Could not locate element with visible text: {text}")
selenium.common.exceptions.NoSuchElementException: Message: Could not locate element with visible text: 23B Old Kiln Road; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/uk_bin_collection/sensor.py", line 68, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 272, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Message: Could not locate element with visible text: 23B Old Kiln Road; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.11/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
I just tested it with my setup and it works @andy-81 

You need to enter the address exactly like its displayed on this screen (Upper case and all) see this file https://github.com/robbrad/UKBinCollectionData/blob/master/uk_bin_collection/tests/input.json#L102

![image](https://github.com/robbrad/UKBinCollectionData/assets/6122503/b3c7246b-8a2e-4184-ae56-c03b920c940b)
