### ISSUE TITLE
Docker build is failing

### ISSUE THREAD

**Issue by andypiper** [robbrad/UKBinCollectionData#551]
This currently fails on both macOS and Linux. I'm not a Dockerfile / build expert so I'm not quite sure what to check here, but on both Mac and Linux I'm seeing it fail somewhere around the Meson section failing to find a compiler.

```text
$ docker build -t ukbc_api_server .
[+] Building 369.3s (8/9)                                                                                                                                                                                docker:default
 => [internal] load .dockerignore                                                                                                                                                                                  0.3s
 => => transferring context: 2B                                                                                                                                                                                    0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                               0.3s
 => => transferring dockerfile: 709B                                                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/python:alpine                                                                                                                                                   2.6s
 => [1/5] FROM docker.io/library/python:alpine@sha256:c793b92fd9e0e2a0b611756788a033d569ca864b733461c8fb30cfd14847dbcf                                                                                            30.5s
 => => resolve docker.io/library/python:alpine@sha256:c793b92fd9e0e2a0b611756788a033d569ca864b733461c8fb30cfd14847dbcf                                                                                             0.3s
 => => sha256:58a674596c42e06b4f9e907a65c44f06fc732a8895156af0cde525415bff379d 11.80MB / 11.80MB                                                                                                                   5.5s
 => => sha256:c793b92fd9e0e2a0b611756788a033d569ca864b733461c8fb30cfd14847dbcf 1.65kB / 1.65kB                                                                                                                     0.0s
 => => sha256:048cac7fc4b34aa1bddfa553e099888f7d656bb8f1e647a5cd5a7073e91a0f89 1.37kB / 1.37kB                                                                                                                     0.0s
 => => sha256:76511bb2b80b6d925fd6f94e8d0566f7a2ba686c2a5cdc6ec9bb3a8a211a8c02 6.06kB / 6.06kB                                                                                                                     0.0s
 => => sha256:c303524923177661067f7eb378c3dd5277088c2676ebd1cd78e68397bb80fdbf 3.35MB / 3.35MB                                                                                                                     2.8s
 => => sha256:e853c0f38ea7ee895b324be2572635fb61172c5bb439c16909ff93c5626bf9e3 624.72kB / 624.72kB                                                                                                                 0.6s
 => => sha256:f368978ed9b20ae320d2fe99c8bd12216564a32890ab05ab3e16b67b4e8e0087 240B / 240B                                                                                                                         1.4s
 => => sha256:3e2894678f740a8e2b3a19717b9e80b2276607078eaa95f75a0881b1bf3001bd 2.68MB / 2.68MB                                                                                                                     3.7s
 => => extracting sha256:c303524923177661067f7eb378c3dd5277088c2676ebd1cd78e68397bb80fdbf                                                                                                                          1.7s
 => => extracting sha256:e853c0f38ea7ee895b324be2572635fb61172c5bb439c16909ff93c5626bf9e3                                                                                                                          2.4s
 => => extracting sha256:58a674596c42e06b4f9e907a65c44f06fc732a8895156af0cde525415bff379d                                                                                                                          7.6s
 => => extracting sha256:f368978ed9b20ae320d2fe99c8bd12216564a32890ab05ab3e16b67b4e8e0087                                                                                                                          0.0s
 => => extracting sha256:3e2894678f740a8e2b3a19717b9e80b2276607078eaa95f75a0881b1bf3001bd                                                                                                                          3.0s
 => [internal] load build context                                                                                                                                                                                  0.2s
 => => transferring context: 4.95kB                                                                                                                                                                                0.0s
 => [2/5] WORKDIR /app                                                                                                                                                                                             0.3s
 => [3/5] COPY requirements.txt .                                                                                                                                                                                  0.3s
 => ERROR [4/5] RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev     && pip install --no-cache-dir -r requirements.txt     && apk del gcc musl-dev libffi-dev openssl-dev                              334.5s
------
 > [4/5] RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev     && pip install --no-cache-dir -r requirements.txt     && apk del gcc musl-dev libffi-dev openssl-dev:
2.017 fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/aarch64/APKINDEX.tar.gz
3.045 fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/aarch64/APKINDEX.tar.gz
6.923 (1/17) Installing libgcc (13.2.1_git20231014-r0)
6.976 (2/17) Installing jansson (2.14-r4)
7.009 (3/17) Installing libstdc++ (13.2.1_git20231014-r0)
7.288 (4/17) Installing zstd-libs (1.5.5-r8)
7.409 (5/17) Installing binutils (2.41-r0)
8.729 (6/17) Installing libgomp (13.2.1_git20231014-r0)
8.804 (7/17) Installing libatomic (13.2.1_git20231014-r0)
8.828 (8/17) Installing gmp (6.3.0-r0)
8.944 (9/17) Installing isl26 (0.26-r1)
9.199 (10/17) Installing mpfr4 (4.2.1-r0)
9.314 (11/17) Installing mpc1 (1.3.1-r1)
9.359 (12/17) Installing gcc (13.2.1_git20231014-r0)
25.76 (13/17) Installing linux-headers (6.5-r0)
32.90 (14/17) Installing pkgconf (2.1.0-r0)
33.01 (15/17) Installing libffi-dev (3.4.4-r3)
33.06 (16/17) Installing musl-dev (1.2.4_git20230717-r4)
34.12 (17/17) Installing openssl-dev (3.1.4-r2)
34.43 Executing busybox-1.36.1-r15.trigger
34.56 OK: 170 MiB in 55 packages
73.72 Collecting connexion (from -r requirements.txt (line 1))
73.72   Obtaining dependency information for connexion from https://files.pythonhosted.org/packages/e5/27/b4391abbe6f19c6016e9ef496976ad7cb4b3f0d440446fc633354c0d7109/connexion-3.0.5-py3-none-any.whl.metadata
74.10   Downloading connexion-3.0.5-py3-none-any.whl.metadata (12 kB)
74.60 Collecting uvicorn (from -r requirements.txt (line 2))
74.60   Obtaining dependency information for uvicorn from https://files.pythonhosted.org/packages/26/59/fddd9df489fe27f492cc97626e03663fb3b9b6ef7ce8597a7cdc5f2cbbad/uvicorn-0.25.0-py3-none-any.whl.metadata
74.64   Downloading uvicorn-0.25.0-py3-none-any.whl.metadata (6.4 kB)
75.36 Collecting uk-bin-collection (from -r requirements.txt (line 5))
75.36   Obtaining dependency information for uk-bin-collection from https://files.pythonhosted.org/packages/b6/46/db5bc8957e6606e1ff5d75761dd54041fcc1cfe6ac6c258f3b12a5de35ec/uk_bin_collection-0.56.11-py3-none-any.whl.metadata
75.40   Downloading uk_bin_collection-0.56.11-py3-none-any.whl.metadata (12 kB)
75.86 Collecting Jinja2>=3.0.0 (from connexion->-r requirements.txt (line 1))
75.89   Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
75.96      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 3.5 MB/s eta 0:00:00
76.70 Collecting PyYAML>=5.1 (from connexion->-r requirements.txt (line 1))
76.74   Downloading PyYAML-6.0.1.tar.gz (125 kB)
76.79      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.2/125.2 kB 4.8 MB/s eta 0:00:00
79.76   Installing build dependencies: started
123.7   Installing build dependencies: finished with status 'done'
123.7   Getting requirements to build wheel: started
145.3   Getting requirements to build wheel: finished with status 'done'
145.4   Preparing metadata (pyproject.toml): started
149.2   Preparing metadata (pyproject.toml): finished with status 'done'
149.5 Collecting asgiref>=3.4 (from connexion->-r requirements.txt (line 1))
149.5   Obtaining dependency information for asgiref>=3.4 from https://files.pythonhosted.org/packages/9b/80/b9051a4a07ad231558fcd8ffc89232711b4e618c15cb7a392a17384bbeef/asgiref-3.7.2-py3-none-any.whl.metadata
149.6   Downloading asgiref-3.7.2-py3-none-any.whl.metadata (9.2 kB)
150.0 Collecting httpx>=0.23 (from connexion->-r requirements.txt (line 1))
150.0   Obtaining dependency information for httpx>=0.23 from https://files.pythonhosted.org/packages/39/9b/4937d841aee9c2c8102d9a4eeb800c7dad25386caabb4a1bf5010df81a57/httpx-0.26.0-py3-none-any.whl.metadata
150.1   Downloading httpx-0.26.0-py3-none-any.whl.metadata (7.6 kB)
150.2 Collecting inflection>=0.3.1 (from connexion->-r requirements.txt (line 1))
150.2   Downloading inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
150.8 Collecting jsonschema>=4.0.1 (from connexion->-r requirements.txt (line 1))
150.8   Obtaining dependency information for jsonschema>=4.0.1 from https://files.pythonhosted.org/packages/0f/ed/0058234d8dd2b1fc6beeea8eab945191a05e9d391a63202f49fe23327586/jsonschema-4.20.0-py3-none-any.whl.metadata
150.9   Downloading jsonschema-4.20.0-py3-none-any.whl.metadata (8.1 kB)
151.0 Collecting python-multipart>=0.0.5 (from connexion->-r requirements.txt (line 1))
151.0   Downloading python_multipart-0.0.6-py3-none-any.whl (45 kB)
151.0      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 5.8 MB/s eta 0:00:00
151.6 Collecting requests>=2.27 (from connexion->-r requirements.txt (line 1))
151.6   Obtaining dependency information for requests>=2.27 from https://files.pythonhosted.org/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl.metadata
151.7   Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
152.2 Collecting starlette<0.33,>=0.27 (from connexion->-r requirements.txt (line 1))
152.2   Obtaining dependency information for starlette<0.33,>=0.27 from https://files.pythonhosted.org/packages/40/9e/6bfa6be40034fa04cc50e2a81d24a4e5b89279c688b51380d70ac31c0556/starlette-0.32.0.post1-py3-none-any.whl.metadata
152.3   Downloading starlette-0.32.0.post1-py3-none-any.whl.metadata (5.8 kB)
152.5 Collecting typing-extensions>=4 (from connexion->-r requirements.txt (line 1))
152.5   Obtaining dependency information for typing-extensions>=4 from https://files.pythonhosted.org/packages/b7/f4/6a90020cd2d93349b442bfcb657d0dc91eee65491600b2cb1d388bc98e6b/typing_extensions-4.9.0-py3-none-any.whl.metadata
152.6   Downloading typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
153.1 Collecting werkzeug>=2.2.1 (from connexion->-r requirements.txt (line 1))
153.1   Obtaining dependency information for werkzeug>=2.2.1 from https://files.pythonhosted.org/packages/c3/fc/254c3e9b5feb89ff5b9076a23218dafbc99c96ac5941e900b71206e6313b/werkzeug-3.0.1-py3-none-any.whl.metadata
153.1   Downloading werkzeug-3.0.1-py3-none-any.whl.metadata (4.1 kB)
153.6 Collecting click>=7.0 (from uvicorn->-r requirements.txt (line 2))
153.6   Obtaining dependency information for click>=7.0 from https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl.metadata
153.6   Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
153.8 Collecting h11>=0.8 (from uvicorn->-r requirements.txt (line 2))
153.8   Downloading h11-0.14.0-py3-none-any.whl (58 kB)
153.8      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 7.8 MB/s eta 0:00:00
154.2 Collecting a2wsgi>=1.7 (from connexion->-r requirements.txt (line 1))
154.2   Obtaining dependency information for a2wsgi>=1.7 from https://files.pythonhosted.org/packages/f3/79/f11e78444458d7c3734619481e62c49397e237bdc2faa2d405999b45b49a/a2wsgi-1.10.0-py3-none-any.whl.metadata
154.2   Downloading a2wsgi-1.10.0-py3-none-any.whl.metadata (3.5 kB)
154.6 Collecting flask[async]>=2.2 (from connexion->-r requirements.txt (line 1))
154.6   Obtaining dependency information for flask[async]>=2.2 from https://files.pythonhosted.org/packages/36/42/015c23096649b908c809c69388a805a571a3bea44362fe87e33fc3afa01f/flask-3.0.0-py3-none-any.whl.metadata
154.6   Downloading flask-3.0.0-py3-none-any.whl.metadata (3.6 kB)
154.9 Collecting swagger-ui-bundle>=1.1.0 (from connexion->-r requirements.txt (line 1))
154.9   Obtaining dependency information for swagger-ui-bundle>=1.1.0 from https://files.pythonhosted.org/packages/a2/66/8fb11445940bde7ca328d6aa23dd36b6056197d862f4bd6bb51c820c50e5/swagger_ui_bundle-1.1.0-py3-none-any.whl.metadata
154.9   Downloading swagger_ui_bundle-1.1.0-py3-none-any.whl.metadata (3.4 kB)
155.1 Collecting bs4 (from uk-bin-collection->-r requirements.txt (line 5))
155.1   Downloading bs4-0.0.1.tar.gz (1.1 kB)
155.2   Preparing metadata (setup.py): started
160.6   Preparing metadata (setup.py): finished with status 'done'
160.9 Collecting holidays (from uk-bin-collection->-r requirements.txt (line 5))
161.0   Obtaining dependency information for holidays from https://files.pythonhosted.org/packages/5d/8c/bad7c11afc8969834728c0678bbf8f3ec5dba4c4ac7f5ad8cf91d63e865f/holidays-0.40-py3-none-any.whl.metadata
161.0   Downloading holidays-0.40-py3-none-any.whl.metadata (21 kB)
164.2 Collecting lxml (from uk-bin-collection->-r requirements.txt (line 5))
164.2   Obtaining dependency information for lxml from https://files.pythonhosted.org/packages/c3/19/b7644b40df5d04e76de550a50d0251ee5efebd18f7cf65675ecfc020a8f5/lxml-5.1.0-cp312-cp312-musllinux_1_1_aarch64.whl.metadata
164.3   Downloading lxml-5.1.0-cp312-cp312-musllinux_1_1_aarch64.whl.metadata (3.5 kB)
166.8 Collecting pandas (from uk-bin-collection->-r requirements.txt (line 5))
166.9   Downloading pandas-2.1.4.tar.gz (4.3 MB)
168.1      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 3.6 MB/s eta 0:00:00
175.4   Installing build dependencies: started
292.2   Installing build dependencies: still running...
294.1   Installing build dependencies: finished with status 'done'
294.1   Getting requirements to build wheel: started
297.6   Getting requirements to build wheel: finished with status 'done'
297.8   Installing backend dependencies: started
310.3   Installing backend dependencies: finished with status 'done'
310.3   Preparing metadata (pyproject.toml): started
326.8   Preparing metadata (pyproject.toml): finished with status 'error'
326.8   error: subprocess-exited-with-error
326.8
326.8   × Preparing metadata (pyproject.toml) did not run successfully.
326.8   │ exit code: 1
326.8   ╰─> [22 lines of output]
326.8       + meson setup /tmp/pip-install-jr0nm9xw/pandas_89ae00f0362b40f8b9021cb3aa478bee /tmp/pip-install-jr0nm9xw/pandas_89ae00f0362b40f8b9021cb3aa478bee/.mesonpy-5o0qxgvt/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=/tmp/pip-install-jr0nm9xw/pandas_89ae00f0362b40f8b9021cb3aa478bee/.mesonpy-5o0qxgvt/build/meson-python-native-file.ini
326.8       The Meson build system
326.8       Version: 1.2.1
326.8       Source dir: /tmp/pip-install-jr0nm9xw/pandas_89ae00f0362b40f8b9021cb3aa478bee
326.8       Build dir: /tmp/pip-install-jr0nm9xw/pandas_89ae00f0362b40f8b9021cb3aa478bee/.mesonpy-5o0qxgvt/build
326.8       Build type: native build
326.8       Project name: pandas
326.8       Project version: 2.1.4
326.8       C compiler for the host machine: cc (gcc 13.2.1 "cc (Alpine 13.2.1_git20231014) 13.2.1 20231014")
326.8       C linker for the host machine: cc ld.bfd 2.41
326.8
326.8       ../../meson.build:2:0: ERROR: Unknown compiler(s): [['c++'], ['g++'], ['clang++'], ['nvc++'], ['pgc++'], ['icpc'], ['icpx']]
326.8       The following exception(s) were encountered:
326.8       Running `c++ --version` gave "[Errno 2] No such file or directory: 'c++'"
326.8       Running `g++ --version` gave "[Errno 2] No such file or directory: 'g++'"
326.8       Running `clang++ --version` gave "[Errno 2] No such file or directory: 'clang++'"
326.8       Running `nvc++ --version` gave "[Errno 2] No such file or directory: 'nvc++'"
326.8       Running `pgc++ --version` gave "[Errno 2] No such file or directory: 'pgc++'"
326.8       Running `icpc --version` gave "[Errno 2] No such file or directory: 'icpc'"
326.8       Running `icpx --version` gave "[Errno 2] No such file or directory: 'icpx'"
326.8
326.8       A full log can be found at /tmp/pip-install-jr0nm9xw/pandas_89ae00f0362b40f8b9021cb3aa478bee/.mesonpy-5o0qxgvt/build/meson-logs/meson-log.txt
326.8       [end of output]
326.8
326.8   note: This error originates from a subprocess, and is likely not a problem with pip.
326.9 error: metadata-generation-failed
326.9
326.9 × Encountered error while generating package metadata.
326.9 ╰─> See above for output.
326.9
326.9 note: This is an issue with the package mentioned above, not pip.
326.9 hint: See above for details.
328.1
328.1 [notice] A new release of pip is available: 23.2.1 -> 23.3.2
328.1 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:11
--------------------
  10 |     # Install any needed packages specified in requirements.txt
  11 | >>> RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev \
  12 | >>>     && pip install --no-cache-dir -r requirements.txt \
  13 | >>>     && apk del gcc musl-dev libffi-dev openssl-dev
  14 |
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add --no-cache gcc musl-dev libffi-dev openssl-dev     && pip install --no-cache-dir -r requirements.txt     && apk del gcc musl-dev libffi-dev openssl-dev" did not complete successfully: exit code: 1
```

**Comment by robbrad** [comment]
@andypiper - the image is also published to docker hub if you need it sooner

**Comment by andypiper** [comment]
No rush; I tested via Docker Compose on my Mac and I'm seeing this error out on being called for Kingston upon Thames, with the error that existed prior to #546 / #547

Thanks.

**Comment by robbrad** [comment]
@andypiper : Can you try doing a docker build with the following file instead

```
# Use an official Python runtime as a parent image
FROM python:alpine

# Set the working directory in the container
WORKDIR /app

# Copy only the requirements file initially
COPY requirements.txt .
RUN apk add --no-cache gcc g++ musl-dev libffi-dev openssl-dev \
    && pip install --no-cache-dir -r requirements.txt \
    # Remove the following line if these dependencies are needed at runtime
    && apk del gcc g++ musl-dev libffi-dev openssl-dev
    
# Copy the application code into the container
COPY . .

# Expose the port for the ukbc server to run on
EXPOSE 8080

# Command to run your application using Uvicorn
CMD ["uvicorn", "server:create_app", "--host", "0.0.0.0", "--port", "8080"]

```

**Comment by andypiper** [comment]
Yes, this builds.

However, I'm seeing:

```text
$ docker run ukbc_api_server                                                                                                                                               ──(Mon,Jan08)─┘
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/app/server.py", line 4, in <module>
    from uk_bin_collection.uk_bin_collection.collect_data import UKBinCollectionApp
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 6, in <module>
    from uk_bin_collection.uk_bin_collection.get_bin_data import (
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 13, in <module>
    from uk_bin_collection.uk_bin_collection.common import update_input_json
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/common.py", line 5, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.12/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/groupby/generic.py", line 67, in <module>
    from pandas.core.frame import DataFrame
  File "/usr/local/lib/python3.12/site-packages/pandas/core/frame.py", line 142, in <module>
    from pandas.core.generic import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/generic.py", line 187, in <module>
    from pandas.core.window import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (
  File "/usr/local/lib/python3.12/site-packages/pandas/core/window/ewm.py", line 11, in <module>
    import pandas._libs.window.aggregations as window_aggregations
ImportError: Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/lib/python3.12/site-packages/pandas/_libs/window/aggregations.cpython-312-aarch64-linux-musl.so)
```

**Comment by andypiper** [comment]
The Docker build & run succeeds on Fedora 39 with that replacement `Dockerfile`, FWIW.

I'm failing to get the Kingston API to work in the container, though. This may be because I am driving it incorrectly? I've got both Docker containers (fresh-built `ukbc_api_server`, and the  `selenium/standalone-chrome:latest` specified in the `docker-compose.yml` running alongside one another; then attempt to use Swagger UI or curl to hit the API endpoint specifying the council name, and the required URL, with or without the web driver parameter, and I'm seeing Python exceptions in the webdriver Remote call with a connection refused.

**Comment by andypiper** [comment]
Aha. It's a Docker network thing. 

Selenium container was on 172.18.0.2:4444 and when I switched to using that (not localhost) in the `web_driver` parameter, I was successful in making a call from host -> ukbc_api_server (via selenium to council).

There's still the build issue on some systems, and I don't know if anything can be done to smooth the docker compose path so it doesn't need the extra network knowledge, but this is good. Apologies if I am falling at hurdles I should be familiar with already!

**Comment by robbrad** [comment]
This repos purpose is to provide council binding data in an automated way, but I know @dp247 and @OliverCullimore will agree, this is a learning project and I love seeing people picking up new skills.

Let this project continue to be a vehicle for that!!

**Comment by dp247** [comment]
Too right. Please don't apologise for things like this, it's exactly what this project is for!

**Comment by robbrad** [comment]
Closing - propose rasing an issue when a build fails for a particular OS
