### ISSUE TITLE
Cheshire West & Chester Council Sensor Bug

### ISSUE THREAD

**Issue by jamescorday** [robbrad/UKBinCollectionData#693]
### Name of Council

Cheshire West & Chester Council 

### Issue Information

```
This error originated from a custom integration.

Logger: custom_components.uk_bin_collection.sensor
Source: helpers/update_coordinator.py:315
integration: UK Bin Collection Data (documentation, issues)
First occurred: 14:29:05 (1 occurrences)
Last logged: 14:29:05

Unexpected error fetching Home data: Message: element click intercepted: Element is not clickable at point (174, 901) (Session info: chrome-headless-shell=124.0.6367.78) Stacktrace: #0 0x00558d227d44 <unknown> #1 0x00558cf4e374 <unknown> #2 0x00558cf8fb44 <unknown> #3 0x00558cf8e778 <unknown> #4 0x00558cf8cf7c <unknown> #5 0x00558cf8c734 <unknown> #6 0x00558cf838a4 <unknown> #7 0x00558cf83370 <unknown> #8 0x00558cfc8400 <unknown> #9 0x00558cf814a4 <unknown> #10 0x00558cf820e0 <unknown> #11 0x00558d1f5ac0 <unknown> #12 0x00558d1f8a64 <unknown> #13 0x00558d1f8630 <unknown> #14 0x00558d1e6d6c <unknown> #15 0x00558d1f9128 <unknown> #16 0x00558d1d1010 <unknown> #17 0x00558d218550 <unknown> #18 0x00558d218758 <unknown> #19 0x00558d227250 <unknown> #20 0x007f87cfee58 <unknown> #21 0x007f87d67f9c <unknown>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/uk_bin_collection/sensor.py", line 133, in _async_update_data
    data = await self.hass.async_add_executor_job(self.ukbcd.run)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 96, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 115, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 78, in template_method
    bin_data_dict = self.parse_data(
                    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/CheshireWestAndChesterCouncil.py", line 55, in parse_data
    find_collection_button.click()
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (174, 901)
  (Session info: chrome-headless-shell=124.0.6367.78)
Stacktrace:
#0 0x00558d227d44 <unknown>
#1 0x00558cf4e374 <unknown>
#2 0x00558cf8fb44 <unknown>
#3 0x00558cf8e778 <unknown>
#4 0x00558cf8cf7c <unknown>
#5 0x00558cf8c734 <unknown>
#6 0x00558cf838a4 <unknown>
#7 0x00558cf83370 <unknown>
#8 0x00558cfc8400 <unknown>
#9 0x00558cf814a4 <unknown>
#10 0x00558cf820e0 <unknown>
#11 0x00558d1f5ac0 <unknown>
#12 0x00558d1f8a64 <unknown>
#13 0x00558d1f8630 <unknown>
#14 0x00558d1e6d6c <unknown>
#15 0x00558d1f9128 <unknown>
#16 0x00558d1d1010 <unknown>
#17 0x00558d218550 <unknown>
#18 0x00558d218758 <unknown>
#19 0x00558d227250 <unknown>
#20 0x007f87cfee58 <unknown>
#21 0x007f87d67f9c <unknown>
```
Hi, getting the above error from Home Assistant when I add the council options. I'm using seleniarm in docker and tested Arun Council and this one works okay and I get a response.

Thanks

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
@jamescorday - I have fixed this as the site had changed. One small change for you - you are going to need the UPRN of your property : see https://uprn.uk

**Comment by jamescorday** [comment]
Thankyou @robbrad 🙂

**Comment by robbrad** [comment]
@jamescorday  : Release is running now.... Refresh your custom comp.

**Comment by jamescorday** [comment]
Working now, thanks @robbrad 
![Screenshot 2024-05-18 at 11 03 22](https://github.com/robbrad/UKBinCollectionData/assets/121184812/b298b622-1ef1-46a7-b5f8-d02f3c63493d)
