### ISSUE TITLE
Norwich City Council Request

### ISSUE THREAD

**Issue by MCSstrike** [robbrad/UKBinCollectionData#749]
### Name of Council

Norwich City Council

### Example Address/Postcode

NR5 8DL

### Additional Information

https://maps.norwich.gov.uk/mynorwich/index.html

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by doomedramen** [comment]
I'll have a look into this tomorrow as it would help me too

**Comment by doomedramen** [comment]
@robbrad 
I took a quick stab at it:
https://github.com/doomedramen/UKBinCollectionData/blob/master/uk_bin_collection/uk_bin_collection/councils/NorwichCityCouncil.py

was hard for me to test it IN HA but it worked for me locally in selenium.

no worries if its not of interest.

**Comment by robbrad** [comment]
Looks good to me! 

If you add an entry in the input.json then raise a PR I'll merge it.

Also if you use the dev container in this repo with VSCode you can actually test this out - see the contributing.md for help

Thanks for this
Rob

**Comment by Alcedema** [comment]
Looking forward to this being in release!

**Comment by doomedramen** [comment]
Sorry for the delay on this.
Attempted to use the Dev Containers but got this error:

```
 > [devcontainer ukbc-dev-base 4/9] RUN apt-get update && apt-get install -y google-chrome-stable:
0.170 Hit:1 https://dl.yarnpkg.com/debian stable InRelease                      
0.220 Get:2 http://dl.google.com/linux/chrome/deb stable InRelease [1825 B]     
0.285 Get:3 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1081 B]
0.691 Hit:4 http://deb.debian.org/debian bullseye InRelease                     
0.698 Get:5 http://deb.debian.org/debian-security bullseye-security InRelease [27.2 kB]
0.710 Hit:6 http://deb.debian.org/debian bullseye-updates InRelease
0.834 Fetched 30.1 kB in 1s (40.6 kB/s)
0.834 Reading package lists...
1.047 Reading package lists...
1.253 Building dependency tree...
1.304 Reading state information...
1.349 E: Unable to locate package google-chrome-stable
------
failed to solve: process "/bin/sh -c apt-get update && apt-get install -y google-chrome-stable" did not complete successfully: exit code: 100
[2174 ms] Error: Command failed: docker compose --project-name ukbincollectiondata_devcontainer -f /Users/martinpage/Developer/UKBinCollectionData/.devcontainer/docker-compose.yml -f /Users/martinpage/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1729161334419.yml build
[2174 ms]     at Pm (/Users/martinpage/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js:430:525)
[2174 ms]     at async ftA (/Users/martinpage/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js:430:2476)
[2175 ms]     at async htA (/Users/martinpage/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js:410:3496)
[2175 ms]     at async TtA (/Users/martinpage/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js:482:4021)
[2175 ms]     at async iB (/Users/martinpage/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js:482:4963)
[2175 ms]     at async wrA (/Users/martinpage/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js:663:203)
[2175 ms]     at async DrA (/Users/martinpage/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js:662:14830)
[2175 ms]     at async /Users/martinpage/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js:482:1190
[2177 ms] Exit code 1
[2178 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/martinpage/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/martinpage/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-01bd02e6-d303-416c-8204-c4e734582efe1729161333379 --workspace-folder /Users/martinpage/Developer/UKBinCollectionData --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=/Users/martinpage/Developer/UKBinCollectionData --id-label devcontainer.config_file=/Users/martinpage/Developer/UKBinCollectionData/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/martinpage/Developer/UKBinCollectionData/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2178 ms] Exit code 1
```
and didn't get around to retrying
