### ISSUE TITLE
Neath Port Talbot updated website

### ISSUE THREAD

**Issue by jezza10d** [robbrad/UKBinCollectionData#768]
### Name of Council

Neath Port Talbot

### Issue Information

Neath Port Talbot appear to have updated their website so the scrapper is no longer working.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by dp247** [comment]
Could you provide any logs to show what's changed?

**Comment by jezza10d** [comment]
I did not have it setup previously as it was throwing errors. I thought it was a similar issue to another user but it was confirmed my issue was unrelated and that is should report that they have updated the webpage.

My logs from HA are as below

```
`This error originated from a custom integration.

Logger: custom_components.uk_bin_collection.sensor
Source: helpers/update_coordinator.py:312
integration: UK Bin Collection Data (documentation, issues)
First occurred: 6:03:21 PM (2 occurrences)
Last logged: 6:58:59 PM

Unexpected error fetching Bridge Street data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/uk_bin_collection/sensor.py", line 139, in _async_update_data
    data = await self.hass.async_add_executor_job(self.ukbcd.run)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 84, in get_and_parse_data
    bin_data_dict = self.parse_data("", url=address_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/NeathPortTalbotCouncil.py", line 34, in parse_data
    driver.get("https://www.npt.gov.uk/2195")
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in get
    self.execute(Command.GET, {"url": url})
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome-headless-shell=125.0.6422.76)
Stacktrace:
#0 0x55c5699e0e9a <unknown>
#1 0x55c5696ca45c <unknown>
#2 0x55c5696c1fd0 <unknown>
#3 0x55c5696b1b32 <unknown>
#4 0x55c5696b3162 <unknown>
#5 0x55c5696b1ded <unknown>
#6 0x55c5696b1503 <unknown>
#7 0x55c5696b13f5 <unknown>
#8 0x55c5696af336 <unknown>
#9 0x55c5696af83a <unknown>
#10 0x55c5696ccea7 <unknown>
#11 0x55c569758ed5 <unknown>
#12 0x55c5697394b2 <unknown>
#13 0x55c5697582cc <unknown>
#14 0x55c569739253 <unknown>
#15 0x55c5697091c7 <unknown>
#16 0x55c569709b3e <unknown>
#17 0x55c5699a72db <unknown>
#18 0x55c5699ab387 <unknown>
#19 0x55c569993e0e <unknown>
#20 0x55c5699abe52 <unknown>
#21 0x55c5699787af <unknown>
#22 0x55c5699d0188 <unknown>
#23 0x55c5699d035b <unknown>
#24 0x55c5699dffcc <unknown>
#25 0x7f4bec02fac3 <unknown>
`
```
