### ISSUE TITLE
Wokingham Council 

### ISSUE THREAD

**Issue by jverBel** [robbrad/UKBinCollectionData#792]
### Name of Council

Wokingham Borough Council

### Example Address/Postcode

RG10 0AN

### Additional Information

https://www.wokingham.gov.uk/rubbish-and-recycling/waste-collection/find-your-bin-collection-day

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by jacklau16** [comment]
Hi, can you assign this request to me as I have started working on it 🙂

**Comment by robbrad** [comment]
Done thanks for working on this !

**Comment by Rujith** [comment]
Is this working ? I am getting errors 

<details>

<summary>Error</summary>

`
2024-10-13 21:44:24.912 ERROR (MainThread) [custom_components.uk_bin_collection.sensor] Unexpected error fetching Wokingham data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/uk_bin_collection/sensor.py", line 153, in _async_update_data
    data = await self.hass.async_add_executor_job(self.ukbcd.run)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 84, in get_and_parse_data
    bin_data_dict = self.parse_data("", url=address_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/WokinghamBoroughCouncil.py", line 33, in parse_data
    driver = create_webdriver(web_driver, headless, None, __name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/common.py", line 325, in create_webdriver
    return webdriver.Chrome(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 101, in start
    self._start_process(self._path)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 211, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver'
2024-10-13 21:44:24.926 ERROR (MainThread) [homeassistant.helpers.entity_platform] uk_bin_collection raises exception ConfigEntryNotReady in forwarded platform sensor; Instead raise ConfigEntryNotReady before calling async_forward_entry_setups
2024-10-13 21:44:46.744 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ 'orange' if is_state(entity, 'on') else 'disabled' }}) renders=82>
Traceback (most recent call last):
`
<\details>

**Comment by jacklau16** [comment]
In fact I got the same error in HA.  I tested with command line in my local env it worked fine though.  I guess we need to enable HA for us to input the web_driver URL for we're using selenium to scrape the web data.  @robbrad I'm not sure if just adding the following into the /tests/input.json will be enough:

`"web_driver": "http://selenium:4444"`

**Comment by robbrad** [comment]
> In fact I got the same error in HA.  I tested with command line in my local env it worked fine though.  I guess we need to enable HA for us to input the web_driver URL for we're using selenium to scrape the web data.  @robbrad I'm not sure if just adding the following into the /tests/input.json will be enough:
> 
> 
> 
> `"web_driver": "http://selenium:4444"`
> 
> 

Yeh in order for the custom component to show the web driver uri option you need to add web driver to input.json
