### ISSUE TITLE
Was working - now isn't retried setup

### ISSUE THREAD

**Issue by dmsims** [robbrad/UKBinCollectionData#968]
### Name of Council

Torbay

### Issue Information

Torbay used to work - now says unavailable

I have tried deleting the configuring and setting up again (24 hrs ago)

This is from the council's website for my address

"Recycling Box
Your recycling box collection will usually be collected on Mondays

The next date it will be collected is 11 November 2024

Residual Bin
Your residual bin collection will usually be collected every other Monday

The next date it will be collected is 11 November 2024"

Error log in HA

2024-11-06 15:23:45.341 ERROR (MainThread) [custom_components.uk_bin_collection.sensor] [UKBinCollection]  Unexpected error: No bin data found for provided UPRN.
Traceback (most recent call last):
  File "/config/custom_components/uk_bin_collection/sensor.py", line 188, in _async_update_data
    data = await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 84, in get_and_parse_data
    bin_data_dict = self.parse_data("", url=address_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/TorbayCouncil.py", line 38, in parse_data
    raise ValueError("No bin data found for provided UPRN.")
ValueError: No bin data found for provided UPRN.
2024-11-06 15:23:45.346 ERROR (MainThread) [custom_components.uk_bin_collection.sensor] Error fetching TQ26TD data: Unexpected error: No bin data found for provided UPRN.
2024-11-06 15:23:45.347 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up uk_bin_collection platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/uk_bin_collection/sensor.py", line 83, in async_setup_entry
    entities = create_sensor_entities(coordinator, config_entry.entry_id, icon_color_mapping)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/uk_bin_collection/sensor.py", line 127, in create_sensor_entities
    for bin_type in coordinator.data.keys():
                    ^^^^^^^^^^^^^^^^^^^^^

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
@dmsims 

I can see the error

ValueError("No bin data found for provided UPRN.")
ValueError: No bin data found for provided UPRN.
2024-11-06 15:23:45.346 ERROR (MainThread) [custom_components.uk_bin_collection.sensor] Error fetching TQ26TD data: Unexpected error: No bin data found for provided UPRN.

Let me test on my side but I can see tests are passing

**Comment by dmsims** [comment]
The UPRN URL has changed :(

to https://online.torbay.gov.uk/services.bartec/collections

**Comment by robbrad** [comment]
What version of the custom component are you on @dmsims ?

**Comment by dmsims** [comment]
There was an update to 0.114.5 this morning - that works - thank you
