### ISSUE TITLE
Not all future collection dates in calendar

### ISSUE THREAD

**Issue by FirstRulez** [robbrad/UKBinCollectionData#984]
### Name of Council

Bradford MDC

### Issue Information

I have only just installed UKBinCollection for the first time, but was pleased to see that Bradford MDC is already supported (Thanks) however I don't think the integration is able to parse the website data correctly as I am not seeing all the expected future bin collection dates.
There is an error in the logs (which I've captured what I think is the relevant part below) and a screenshot of the Bradford MDC website for my address.
I am only seeing a single calendar entry for the one date mentioned in the logs 15/11/2024, but also expect a collection on 12/11/2024 this week, as well as numerous future dates.

![image](https://github.com/user-attachments/assets/7ad6ed14-a387-41db-af5d-21f5f55c012f)

```
2024-11-10 18:55:00.596 INFO (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Unloading config entry 01JCBP0ZRVYQ10G3BX3HQ798X6.
2024-11-10 18:55:00.596 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Successfully unloaded 'sensor' platform for entry_id=01JCBP0ZRVYQ10G3BX3HQ798X6.
2024-11-10 18:55:00.597 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Successfully unloaded 'calendar' platform for entry_id=01JCBP0ZRVYQ10G3BX3HQ798X6.
2024-11-10 18:55:00.597 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Unloaded and removed coordinator for entry_id=01JCBP0ZRVYQ10G3BX3HQ798X6.
2024-11-10 18:55:00.597 INFO (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Setting up UK Bin Collection.
2024-11-10 18:55:00.597 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Retrieved configuration: name=Home, timeout=60, update_interval=12 hours, icon_color_mapping=100051262991
2024-11-10 18:55:00.597 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Built UKBinCollectionApp arguments: ['BradfordMDC', 'https://onlineforms.bradford.gov.uk/ufs/collectiondates.eb', '--uprn=100051262991']
2024-11-10 18:55:00.597 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  UKBinCollectionApp args: ['BradfordMDC', 'https://onlineforms.bradford.gov.uk/ufs/collectiondates.eb', '--uprn=100051262991']
2024-11-10 18:55:00.598 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  UKBinCollectionApp initialized and arguments set.
2024-11-10 18:55:00.598 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  DataUpdateCoordinator initialized with update_interval=12:00:00.
2024-11-10 18:55:00.598 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  HouseholdBinCoordinator initialized with update_interval=12 hours.
2024-11-10 18:55:00.598 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Starting data fetch with timeout=60 seconds.
2024-11-10 18:55:00.598 INFO (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Fetching latest bin collection data.
2024-11-10 18:55:01.880 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Data fetched: {
    "bins": [
        {
            "type": "Recycling Waste",
            "collectionDate": "15/11/2024"
        }
    ]
}
2024-11-10 18:55:01.880 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Parsed data: {'bins': [{'type': 'Recycling Waste', 'collectionDate': '15/11/2024'}]}
2024-11-10 18:55:01.880 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Updated next collection for 'Recycling Waste' to 2024-11-15.
2024-11-10 18:55:01.880 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Next Collection Dates: {'Recycling Waste': datetime.date(2024, 11, 15)}
2024-11-10 18:55:01.880 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Processed data: {'Recycling Waste': datetime.date(2024, 11, 15)}
2024-11-10 18:55:01.880 INFO (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Bin collection data updated successfully.
2024-11-10 18:55:01.880 DEBUG (MainThread) [custom_components.uk_bin_collection] Finished fetching Home data in 1.282 seconds (success: True)
2024-11-10 18:55:01.880 INFO (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Initial data fetched successfully.
2024-11-10 18:55:01.880 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Coordinator stored in hass.data under entry_id=01JCBP0ZRVYQ10G3BX3HQ798X6.
2024-11-10 18:55:01.881 INFO (MainThread) [custom_components.uk_bin_collection.sensor] [UKBinCollection]  Setting up UK Bin Collection Data platform.
2024-11-10 18:55:01.881 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up uk_bin_collection platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/uk_bin_collection/sensor.py", line 51, in async_setup_entry
    entities = create_sensor_entities(coordinator, config_entry.entry_id, icon_color_mapping)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/uk_bin_collection/sensor.py", line 67, in create_sensor_entities
    UKBinCollectionDataSensor(
  File "/config/custom_components/uk_bin_collection/sensor.py", line 117, in __init__
    self._icon = self.get_icon()
                 ^^^^^^^^^^^^^^^
  File "/config/custom_components/uk_bin_collection/sensor.py", line 170, in get_icon
    return self._icon_color_mapping.get(self._bin_type, {}).get(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'get'
2024-11-10 18:55:01.882 INFO (MainThread) [custom_components.uk_bin_collection.calendar] [UKBinCollection]  Setting up UK Bin Collection Calendar platform.
2024-11-10 18:55:01.883 DEBUG (MainThread) [custom_components.uk_bin_collection.calendar] [UKBinCollection]  Calendar entities added: ['Home Recycling Waste Calendar']
2024-11-10 18:55:01.883 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection]  Setup forwarded to platforms: ['sensor', 'calendar'].
```

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by dp247** [comment]
What does the config in Home Assistant look like? Looks like it's erroring on the icon colour mapping

**Comment by robbrad** [comment]
Agreed with @dp247. @FirstRulez there is an issue in the icons mapping.

Also looking at the screenshot I'm not sure the scraper that was created was ever made to get the bottom table.

Might be a feature request for this council

**Comment by FirstRulez** [comment]
Thank you for sorting this, apologies I don't seem to be getting notifications from GitHub at the moment.
I had the JSON setup as follows, but it appears robbrad has fixed the issue completely for me regardless so all 3 bin types are now showing the next collection in the future.
